apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: module-mirror            
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/franekrocha/module-mirror
    targetRevision: HEAD
