{{- range $key, $val := $.Values.repositories }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-27"
  name: oc-mirror-{{ $key }}
  namespace: {{ $.Values.namespace }}
data:
  imagesetconfiguration.yaml: |
    kind: ImageSetConfiguration
    apiVersion: mirror.openshift.io/v1alpha2
    storageConfig:
      registry:
        imageURL: "{{ $.Values.repository }}/{{ $key }}/metadata"
        skipTLS: true
    mirror:
      operators:
      - catalog: "{{ $val.catalog }}"
        packages:
        {{- range $package, $values := $val. }}
        - name: {{ $package }}
          channels:
          - name: {{ $values.channel }}
            minVersion: {{ $values.version }}
            maxVersion: {{ $values.version }}
        {{- end }}
{{- end }}