{{- $wave := -27 }}
{{- range $key, $val := $.Values.catalogs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "{{ $wave }}"
  name: oc-mirror-{{ $key }}
  namespace: {{ $.Values.namespace }}
data:
  imagesetconfiguration.yaml: |
    kind: ImageSetConfiguration
    apiVersion: mirror.openshift.io/v1alpha2
    storageConfig:
      registry:
        imageURL: "{{ $.Values.path }}/registry.redhat.io/metadata"
        skipTLS: true
    mirror:
      operators:
      - catalog: "{{ $.Values.catalog }}"
        packages:
        {{- range $package, $values := $val.packages }}
        - name: {{ $package }}
          channels:
          - name: {{ $values.channel }}
            minVersion: {{ $values.version }}
            maxVersion: {{ $values.version }}
        {{- end }}
{{ $wave := $wave add 1 }}
{{- end }}
