{{- range $key, $val := $.Values.repositories }}
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-26"
  name: oc-mirror-{{ $key }}
  namespace: {{ $.Values.namespace }}
spec:
  template:
    spec:
      serviceAccountName: oc-mirror
      containers:
      - name: ose-cli
        image: {{ $.Values.image }}
        securityContext:
          runAsUser: 0
        command:
          - "/bin/sh"
          - "-c"
          - |
            cd /root
            wget {{ $.Values.ocMirror }}
            tar xvzf oc-mirror.tar.gz
            chmod +x oc-mirror
            ./oc-mirror --config=/tmp/config/imagesetconfiguration.yaml docker://{{ $.Values.repository }}/{{ $key }} --dest-skip-tls=true
            sed -i "s/name: operator-0/name: {{ $key }}/g" oc-mirror-workspace/results-*/imageContentSourcePolicy.yaml
            sed -i "s/name: redhat-operator-index/name: {{ $key }}/g" oc-mirror-workspace/results-*/catalogSource-redhat-operator-index.yaml
            oc apply -f oc-mirror-workspace/results-*/imageContentSourcePolicy.yaml
            oc apply -f oc-mirror-workspace/results-*/catalogSource-redhat-operator-index.yaml
        volumeMounts:
        - name: imageset-config
          mountPath: /tmp/config
        - name: docker-config
          mountPath: /root/.docker/
      restartPolicy: Never
      volumes:
      - name: imageset-config
        configMap:
          name: oc-mirror-{{ $key }}
      - name: docker-config
        secret:
          secretName: pullsecret
{{- end }}
