apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-26"
  name: oc-mirror-{{ $.Values.name }}-{{ $.Values.version }}
  namespace: {{ $.Values.namespace }}
spec:
  template:
    spec:
      serviceAccountName: oc-mirror-{{ $.Values.name }}-{{ $.Values.version }}
      containers:
      - name: ose-cli
        image: {{ $.Values.image }}
        securityContext:
          runAsUser: 0
        command:
          - "/bin/sh"
          - "-c"
          - |
            cd /root
            wget {{ $.Values.ocMirror }}
            tar xvzf oc-mirror.tar.gz
            chmod +x oc-mirror
            ./oc-mirror --config=/tmp/config/imagesetconfiguration.yaml docker://{{ $.Values.repository }}/{{ $.Values.key }}-{{ $.Values.name }}-{{ $.Values.version }} --dest-skip-tls=true
            oc create -f oc-mirror-workspace/results-*/imageContentSourcePolicy.yaml
            oc create -f oc-mirror-workspace/results-*/catalogSource-redhat-operator-index.yaml
        volumeMounts:
        - name: imageset-config
          mountPath: /tmp/config
        - name: docker-config
          mountPath: /root/.docker/
      restartPolicy: Never
      volumes:
      - name: imageset-config
        configMap:
          name: imagesetconfiguration-{{ $.Values.name }}-{{ $.Values.version }}
      - name: docker-config
        secret:
          secretName: pullsecret-{{ $.Values.name }}-{{ $.Values.version }}
