---
apiVersion: v1
kind: Secret
metadata:
  name: oc-mirror-{{ .Values.name }}-{{ .Values.version }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  config.json: base64-encoded-content-of-pull-secret.txt
