---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-27"
  name: pullsecret-{{ .Values.name }}-{{ .Values.version }}-fake
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  config.json: fake
